{
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/yuminshen/cs61a-2024/blob/main/cg2all.ipynb\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "FBOi_bUBW5dR"
      },
      "source": [
        "\n",
        "# List of tasks\n",
        "- Task 1: Conversion of an all-atom structure to a CG model using __convert_all2cg__\n",
        "- Task 2: Conversion of a CG model to an all-atom structure using __convert_cg2all__\n",
        "- Task 3: Conversion of a CG simulation trajectory to an atomistic simulation trajectory using __convert_cg2all__\n",
        "\n",
        "# Supported coarse-grained models\n",
        "- CalphaBasedModel: C$\\alpha$-trace (atom names should be \"CA\")\n",
        "- ResidueBasedModel: Residue center-of-mass (atom names should be \"CA\")\n",
        "- SidechainModel: A bead at the sidechain center-of-mass (atom names should be \"SC\")\n",
        "- CalphaCMModel: C$\\alpha$-trace + Residue center-of-mass (atom names should be \"CA\" and \"CM\")\n",
        "- CalphaSCModel: C$\\alpha$-trace + Sidechain center-of-mass (atom names should be \"CA\" and \"SC\")\n",
        "- BackboneModel: Model only with backbone atoms (N, CA, C)\n",
        "- MainchainModel: Model only with mainchain atoms (N, CA, C, O)\n",
        "- Martini: [Martini](http://cgmartini.nl/) model\n",
        "- Martini3: [Martini3](http://www.cgmartini.nl/index.php/martini-3-0) model\n",
        "- PRIMO: [PRIMO](http://dx.doi.org/10.1002/prot.22645) model\n",
        "---"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 1,
      "metadata": {
        "id": "pmJA_J_IlU7s",
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "outputId": "0a779b91-58cf-47ad-8330-c1f1ab66085b"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "This notebook is running on a GPU runtime.\n"
          ]
        }
      ],
      "source": [
        "#@title Install cg2all package (takes 4-5 minutes)\n",
        "%%bash\n",
        "\n",
        "gpu_available=$(nvidia-smi | grep \"CUDA Version\" | wc -l)\n",
        "if [[ $gpu_available == 1 ]]; then\n",
        "    echo \"This notebook is running on a GPU runtime.\"\n",
        "    pip install  dgl -f https://data.dgl.ai/wheels/torch-2.3/cu121/repo.html &> /dev/null\n",
        "    #pip install dgl -f https://data.dgl.ai/wheels/cu116/repo.html &> /dev/null\n",
        "else\n",
        "    echo \"This notebook is running on a CPU runtime.\"\n",
        "fi\n",
        "\n",
        "pip install -q git+http://github.com/huhlim/cg2all@cuda-12 &> /dev/null\n",
        "pip install -q py3Dmol gdown mrcfile &> /dev/null"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 2,
      "metadata": {
        "id": "BaywXyY50z7O",
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "outputId": "d73efb94-8c03-458c-fdb7-c42d6694418b"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "DGL backend not selected or invalid.  Assuming PyTorch for now.\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Setting the default backend to \"pytorch\". You can change it in the ~/.dgl/config.json file or export the DGLBACKEND environment variable.  Valid options are: pytorch, mxnet, tensorflow (all lowercase)\n",
            "Downloading from Google Drive ... /usr/local/lib/python3.11/dist-packages/cg2all/model/CalphaBasedModel.ckpt\n",
            "Downloading from Google Drive ... /usr/local/lib/python3.11/dist-packages/cg2all/model/ResidueBasedModel.ckpt\n",
            "Downloading from Google Drive ... /usr/local/lib/python3.11/dist-packages/cg2all/model/SidechainModel.ckpt\n",
            "Downloading from Google Drive ... /usr/local/lib/python3.11/dist-packages/cg2all/model/CalphaCMModel.ckpt\n",
            "Downloading from Google Drive ... /usr/local/lib/python3.11/dist-packages/cg2all/model/CalphaSCModel.ckpt\n",
            "Downloading from Google Drive ... /usr/local/lib/python3.11/dist-packages/cg2all/model/BackboneModel.ckpt\n",
            "Downloading from Google Drive ... /usr/local/lib/python3.11/dist-packages/cg2all/model/MainchainModel.ckpt\n",
            "Downloading from Google Drive ... /usr/local/lib/python3.11/dist-packages/cg2all/model/Martini.ckpt\n",
            "Downloading from Google Drive ... /usr/local/lib/python3.11/dist-packages/cg2all/model/Martini3.ckpt\n",
            "Downloading from Google Drive ... /usr/local/lib/python3.11/dist-packages/cg2all/model/PRIMO.ckpt\n"
          ]
        }
      ],
      "source": [
        "#@title Download model checkpoint files (optional, takes <1 minute)\n",
        "#@markdown This step downloads all PyTorch model checkpoint files. If you did not run this step and a necessary checkpoint file is missing, then the script will download it automatically.\n",
        "\n",
        "import cg2all.lib.libmodel\n",
        "from cg2all.lib.libconfig import MODEL_HOME\n",
        "\n",
        "for model_type in [\"CalphaBasedModel\", \"ResidueBasedModel\", \"SidechainModel\", \"CalphaCMModel\", \"CalphaSCModel\", \"BackboneModel\", \"MainchainModel\", \"Martini\", \"Martini3\", \"PRIMO\"]:\n",
        "    ckpt_fn = MODEL_HOME / f\"{model_type}.ckpt\"\n",
        "    if not ckpt_fn.exists():\n",
        "        cg2all.lib.libmodel.download_ckpt_file(model_type, ckpt_fn)\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 3,
      "metadata": {
        "id": "2izhOiEl_LZz"
      },
      "outputs": [],
      "source": [
        "#@title Set up py3Dmol for structure display\n",
        "\n",
        "import py3Dmol\n",
        "\n",
        "def display(pdb_fn, representation=\"cartoon\", is_traj=False):\n",
        "    view = py3Dmol.view(js='https://3dmol.org/build/3Dmol.js')\n",
        "    if is_traj:\n",
        "        view.addModelsAsFrames(open(pdb_fn,'r').read(),'pdb')\n",
        "    else:\n",
        "        view.addModel(open(pdb_fn,'r').read(),'pdb')\n",
        "\n",
        "    if representation == \"cartoon\":\n",
        "        view.setStyle({'cartoon': {'color':'spectrum'}})\n",
        "        #\n",
        "        view.addStyle({'and':[{'resn':[\"GLY\",\"PRO\"],'invert':True},{'atom': [\"N\", \"C\", \"O\"],'invert':True}]},\n",
        "                        {'stick':{'colorscheme':\"WhiteCarbon\",'radius':0.3}})\n",
        "        view.addStyle({'and':[{'resn':\"GLY\"},{'atom':'CA'}]},\n",
        "                        {'sphere':{'colorscheme':\"WhiteCarbon\",'radius':0.3}})\n",
        "        view.addStyle({'and':[{'resn':\"PRO\"},{'atom':['C','O'],'invert':True}]},\n",
        "                        {'stick':{'colorscheme':\"WhiteCarbon\",'radius':0.3}})\n",
        "\n",
        "    elif representation == \"ball+stick\":\n",
        "        view.setStyle({\"sphere\": {\"color\": \"spectrum\", \"radius\": 1.0}})\n",
        "\n",
        "    else:\n",
        "        raise NotImplementedError(representation)\n",
        "\n",
        "    view.zoomTo()\n",
        "    if is_traj:\n",
        "        view.animate({'loop': 'forward', \"interval\": 500})\n",
        "\n",
        "    return view"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "8B3PrhVv2XjL"
      },
      "source": [
        "---"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "cellView": "form",
        "id": "ZdOjX1AMX7G5"
      },
      "outputs": [],
      "source": [
        "#@title Task 1: Conversion of an all-atom structure to a CG model using __convert_all2cg__\n",
        "\n",
        "# upload a PDB file\n",
        "import requests\n",
        "from google.colab import files\n",
        "\n",
        "coarse_grained_model_type = \"Martini3\" #@param [\"CalphaBasedModel\", \"ResidueBasedModel\", \"SidechainModel\", \"CalphaCMModel\", \"CalphaSCModel\", \"BackboneModel\", \"MainchainModel\", \"Martini\", \"Martini3\", \"PRIMO\"]\n",
        "\n",
        "use_example = True #@param {type:\"boolean\"}\n",
        "#@markdown - An example input PDB file will be downloaded from [our repository](https://github.com/huhlim/cg2all/tree/main/tests).\n",
        "\n",
        "if use_example:\n",
        "    url = \"https://raw.githubusercontent.com/huhlim/cg2all/main/tests/1ab1_A.pdb\"\n",
        "    input_pdb = url.split(\"/\")[-1]\n",
        "    with open(input_pdb, \"wt\") as fout:\n",
        "        fout.write(requests.get(url).text)\n",
        "else:\n",
        "    input_pdb = files.upload()\n",
        "    input_pdb = list(input_pdb)[0]\n",
        "\n",
        "# convert\n",
        "import pathlib\n",
        "output_pdb = pathlib.Path(input_pdb).stem + f\".{coarse_grained_model_type}.pdb\"\n",
        "\n",
        "!convert_all2cg -p $input_pdb -o $output_pdb --cg $coarse_grained_model_type\n",
        "print(f\"Converted {input_pdb} to {output_pdb} in {coarse_grained_model_type}\")\n",
        "\n",
        "display(output_pdb, representation=\"ball+stick\").show()"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "cellView": "form",
        "id": "bT6wD7fOc8hz"
      },
      "outputs": [],
      "source": [
        "#@title Download the converted file\n",
        "files.download(output_pdb)"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "JC-tfBj7c-Oh"
      },
      "source": [
        "---"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 14,
      "metadata": {
        "id": "NKt4ZMqn6W85",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 1000
        },
        "collapsed": true,
        "outputId": "3181eaa5-2ad9-45cb-fba3-f155caf332a2"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Requirement already satisfied: biopython in /usr/local/lib/python3.11/dist-packages (1.85)\n",
            "Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from biopython) (1.26.4)\n",
            "Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount(\"/content/drive\", force_remount=True).\n",
            "Processing: PED00082_C20_S00_GT.pdb -> /content/drive/MyDrive/clustered_ensemble_outputs/PED00082_C20_S00_GT.all.pdb\n",
            "处理 PED00082_C20_S00_GT.pdb 时出错:\n",
            "返回码: 1\n",
            "STDERR: Traceback (most recent call last):\n",
            "  File \"/usr/local/bin/convert_cg2all\", line 8, in <module>\n",
            "    sys.exit(main())\n",
            "             ^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/script/convert_cg2all.py\", line 190, in main\n",
            "    batch = next(iter(input_s)).to(device)\n",
            "            ^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py\", line 630, in __next__\n",
            "    data = self._next_data()\n",
            "           ^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py\", line 1344, in _next_data\n",
            "    return self._process_data(data)\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py\", line 1370, in _process_data\n",
            "    data.reraise()\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/_utils.py\", line 706, in reraise\n",
            "    raise exception\n",
            "OSError: Caught OSError in DataLoader worker process 0.\n",
            "Original Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/_utils/worker.py\", line 309, in _worker_loop\n",
            "    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]\n",
            "           ^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/_utils/fetch.py\", line 52, in fetch\n",
            "    data = [self.dataset[idx] for idx in possibly_batched_index]\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/_utils/fetch.py\", line 52, in <listcomp>\n",
            "    data = [self.dataset[idx] for idx in possibly_batched_index]\n",
            "            ~~~~~~~~~~~~^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libdata.py\", line 333, in __getitem__\n",
            "    cg = self.pdb_to_cg(self.pdb_fn)\n",
            "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libdata.py\", line 313, in pdb_to_cg\n",
            "    return self.cg_model(\n",
            "           ^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libcg.py\", line 248, in __init__\n",
            "    super().__init__(pdb_fn, dcd_fn, **kwarg)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libcg.py\", line 44, in __init__\n",
            "    super().__init__(pdb_fn, dcd_fn, is_all=is_all, **kwarg)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libpdb.py\", line 20, in __init__\n",
            "    pdb = mdtraj.load(pdb_fn, standard_names=False)\n",
            "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 396, in load\n",
            "    kwargs[\"top\"] = _parse_topology(\n",
            "                    ^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 170, in _parse_topology\n",
            "    _traj = load_frame(top, 0, **kwargs)\n",
            "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 309, in load_frame\n",
            "    _assert_files_exist(filename)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 108, in _assert_files_exist\n",
            "    raise OSError(\"No such file: %s\" % fn)\n",
            "OSError: No such file: PED00082_C20_S00_GT.pdb\n",
            "\n",
            "\n",
            "STDOUT: \n",
            "Processing: PED00082_C12_S00_GT.pdb -> /content/drive/MyDrive/clustered_ensemble_outputs/PED00082_C12_S00_GT.all.pdb\n",
            "处理 PED00082_C12_S00_GT.pdb 时出错:\n",
            "返回码: 1\n",
            "STDERR: Traceback (most recent call last):\n",
            "  File \"/usr/local/bin/convert_cg2all\", line 8, in <module>\n",
            "    sys.exit(main())\n",
            "             ^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/script/convert_cg2all.py\", line 190, in main\n",
            "    batch = next(iter(input_s)).to(device)\n",
            "            ^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py\", line 630, in __next__\n",
            "    data = self._next_data()\n",
            "           ^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py\", line 1344, in _next_data\n",
            "    return self._process_data(data)\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py\", line 1370, in _process_data\n",
            "    data.reraise()\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/_utils.py\", line 706, in reraise\n",
            "    raise exception\n",
            "OSError: Caught OSError in DataLoader worker process 0.\n",
            "Original Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/_utils/worker.py\", line 309, in _worker_loop\n",
            "    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]\n",
            "           ^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/_utils/fetch.py\", line 52, in fetch\n",
            "    data = [self.dataset[idx] for idx in possibly_batched_index]\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/_utils/fetch.py\", line 52, in <listcomp>\n",
            "    data = [self.dataset[idx] for idx in possibly_batched_index]\n",
            "            ~~~~~~~~~~~~^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libdata.py\", line 333, in __getitem__\n",
            "    cg = self.pdb_to_cg(self.pdb_fn)\n",
            "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libdata.py\", line 313, in pdb_to_cg\n",
            "    return self.cg_model(\n",
            "           ^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libcg.py\", line 248, in __init__\n",
            "    super().__init__(pdb_fn, dcd_fn, **kwarg)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libcg.py\", line 44, in __init__\n",
            "    super().__init__(pdb_fn, dcd_fn, is_all=is_all, **kwarg)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libpdb.py\", line 20, in __init__\n",
            "    pdb = mdtraj.load(pdb_fn, standard_names=False)\n",
            "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 396, in load\n",
            "    kwargs[\"top\"] = _parse_topology(\n",
            "                    ^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 170, in _parse_topology\n",
            "    _traj = load_frame(top, 0, **kwargs)\n",
            "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 309, in load_frame\n",
            "    _assert_files_exist(filename)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 108, in _assert_files_exist\n",
            "    raise OSError(\"No such file: %s\" % fn)\n",
            "OSError: No such file: PED00082_C12_S00_GT.pdb\n",
            "\n",
            "\n",
            "STDOUT: \n",
            "Processing: PED00082_C06_S00_GT.pdb -> /content/drive/MyDrive/clustered_ensemble_outputs/PED00082_C06_S00_GT.all.pdb\n",
            "处理 PED00082_C06_S00_GT.pdb 时出错:\n",
            "返回码: 1\n",
            "STDERR: Traceback (most recent call last):\n",
            "  File \"/usr/local/bin/convert_cg2all\", line 8, in <module>\n",
            "    sys.exit(main())\n",
            "             ^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/script/convert_cg2all.py\", line 190, in main\n",
            "    batch = next(iter(input_s)).to(device)\n",
            "            ^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py\", line 630, in __next__\n",
            "    data = self._next_data()\n",
            "           ^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py\", line 1344, in _next_data\n",
            "    return self._process_data(data)\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py\", line 1370, in _process_data\n",
            "    data.reraise()\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/_utils.py\", line 706, in reraise\n",
            "    raise exception\n",
            "OSError: Caught OSError in DataLoader worker process 0.\n",
            "Original Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/_utils/worker.py\", line 309, in _worker_loop\n",
            "    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]\n",
            "           ^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/_utils/fetch.py\", line 52, in fetch\n",
            "    data = [self.dataset[idx] for idx in possibly_batched_index]\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/_utils/fetch.py\", line 52, in <listcomp>\n",
            "    data = [self.dataset[idx] for idx in possibly_batched_index]\n",
            "            ~~~~~~~~~~~~^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libdata.py\", line 333, in __getitem__\n",
            "    cg = self.pdb_to_cg(self.pdb_fn)\n",
            "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libdata.py\", line 313, in pdb_to_cg\n",
            "    return self.cg_model(\n",
            "           ^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libcg.py\", line 248, in __init__\n",
            "    super().__init__(pdb_fn, dcd_fn, **kwarg)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libcg.py\", line 44, in __init__\n",
            "    super().__init__(pdb_fn, dcd_fn, is_all=is_all, **kwarg)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libpdb.py\", line 20, in __init__\n",
            "    pdb = mdtraj.load(pdb_fn, standard_names=False)\n",
            "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 396, in load\n",
            "    kwargs[\"top\"] = _parse_topology(\n",
            "                    ^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 170, in _parse_topology\n",
            "    _traj = load_frame(top, 0, **kwargs)\n",
            "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 309, in load_frame\n",
            "    _assert_files_exist(filename)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 108, in _assert_files_exist\n",
            "    raise OSError(\"No such file: %s\" % fn)\n",
            "OSError: No such file: PED00082_C06_S00_GT.pdb\n",
            "\n",
            "\n",
            "STDOUT: \n",
            "Processing: PED00082_C10_S00_GT.pdb -> /content/drive/MyDrive/clustered_ensemble_outputs/PED00082_C10_S00_GT.all.pdb\n",
            "处理 PED00082_C10_S00_GT.pdb 时出错:\n",
            "返回码: 1\n",
            "STDERR: Traceback (most recent call last):\n",
            "  File \"/usr/local/bin/convert_cg2all\", line 8, in <module>\n",
            "    sys.exit(main())\n",
            "             ^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/script/convert_cg2all.py\", line 190, in main\n",
            "    batch = next(iter(input_s)).to(device)\n",
            "            ^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py\", line 630, in __next__\n",
            "    data = self._next_data()\n",
            "           ^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py\", line 1344, in _next_data\n",
            "    return self._process_data(data)\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py\", line 1370, in _process_data\n",
            "    data.reraise()\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/_utils.py\", line 706, in reraise\n",
            "    raise exception\n",
            "OSError: Caught OSError in DataLoader worker process 0.\n",
            "Original Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/_utils/worker.py\", line 309, in _worker_loop\n",
            "    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]\n",
            "           ^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/_utils/fetch.py\", line 52, in fetch\n",
            "    data = [self.dataset[idx] for idx in possibly_batched_index]\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/_utils/fetch.py\", line 52, in <listcomp>\n",
            "    data = [self.dataset[idx] for idx in possibly_batched_index]\n",
            "            ~~~~~~~~~~~~^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libdata.py\", line 333, in __getitem__\n",
            "    cg = self.pdb_to_cg(self.pdb_fn)\n",
            "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libdata.py\", line 313, in pdb_to_cg\n",
            "    return self.cg_model(\n",
            "           ^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libcg.py\", line 248, in __init__\n",
            "    super().__init__(pdb_fn, dcd_fn, **kwarg)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libcg.py\", line 44, in __init__\n",
            "    super().__init__(pdb_fn, dcd_fn, is_all=is_all, **kwarg)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libpdb.py\", line 20, in __init__\n",
            "    pdb = mdtraj.load(pdb_fn, standard_names=False)\n",
            "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 396, in load\n",
            "    kwargs[\"top\"] = _parse_topology(\n",
            "                    ^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 170, in _parse_topology\n",
            "    _traj = load_frame(top, 0, **kwargs)\n",
            "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 309, in load_frame\n",
            "    _assert_files_exist(filename)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 108, in _assert_files_exist\n",
            "    raise OSError(\"No such file: %s\" % fn)\n",
            "OSError: No such file: PED00082_C10_S00_GT.pdb\n",
            "\n",
            "\n",
            "STDOUT: \n",
            "Processing: PED00082_C17_S00_GT.pdb -> /content/drive/MyDrive/clustered_ensemble_outputs/PED00082_C17_S00_GT.all.pdb\n",
            "处理 PED00082_C17_S00_GT.pdb 时出错:\n",
            "返回码: 1\n",
            "STDERR: Traceback (most recent call last):\n",
            "  File \"/usr/local/bin/convert_cg2all\", line 8, in <module>\n",
            "    sys.exit(main())\n",
            "             ^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/script/convert_cg2all.py\", line 190, in main\n",
            "    batch = next(iter(input_s)).to(device)\n",
            "            ^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py\", line 630, in __next__\n",
            "    data = self._next_data()\n",
            "           ^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py\", line 1344, in _next_data\n",
            "    return self._process_data(data)\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py\", line 1370, in _process_data\n",
            "    data.reraise()\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/_utils.py\", line 706, in reraise\n",
            "    raise exception\n",
            "OSError: Caught OSError in DataLoader worker process 0.\n",
            "Original Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/_utils/worker.py\", line 309, in _worker_loop\n",
            "    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]\n",
            "           ^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/_utils/fetch.py\", line 52, in fetch\n",
            "    data = [self.dataset[idx] for idx in possibly_batched_index]\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/_utils/fetch.py\", line 52, in <listcomp>\n",
            "    data = [self.dataset[idx] for idx in possibly_batched_index]\n",
            "            ~~~~~~~~~~~~^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libdata.py\", line 333, in __getitem__\n",
            "    cg = self.pdb_to_cg(self.pdb_fn)\n",
            "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libdata.py\", line 313, in pdb_to_cg\n",
            "    return self.cg_model(\n",
            "           ^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libcg.py\", line 248, in __init__\n",
            "    super().__init__(pdb_fn, dcd_fn, **kwarg)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libcg.py\", line 44, in __init__\n",
            "    super().__init__(pdb_fn, dcd_fn, is_all=is_all, **kwarg)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libpdb.py\", line 20, in __init__\n",
            "    pdb = mdtraj.load(pdb_fn, standard_names=False)\n",
            "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 396, in load\n",
            "    kwargs[\"top\"] = _parse_topology(\n",
            "                    ^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 170, in _parse_topology\n",
            "    _traj = load_frame(top, 0, **kwargs)\n",
            "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 309, in load_frame\n",
            "    _assert_files_exist(filename)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 108, in _assert_files_exist\n",
            "    raise OSError(\"No such file: %s\" % fn)\n",
            "OSError: No such file: PED00082_C17_S00_GT.pdb\n",
            "\n",
            "\n",
            "STDOUT: \n",
            "Processing: PED00082_C24_S00_GT.pdb -> /content/drive/MyDrive/clustered_ensemble_outputs/PED00082_C24_S00_GT.all.pdb\n",
            "处理 PED00082_C24_S00_GT.pdb 时出错:\n",
            "返回码: 1\n",
            "STDERR: Traceback (most recent call last):\n",
            "  File \"/usr/local/bin/convert_cg2all\", line 8, in <module>\n",
            "    sys.exit(main())\n",
            "             ^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/script/convert_cg2all.py\", line 190, in main\n",
            "    batch = next(iter(input_s)).to(device)\n",
            "            ^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py\", line 630, in __next__\n",
            "    data = self._next_data()\n",
            "           ^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py\", line 1344, in _next_data\n",
            "    return self._process_data(data)\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py\", line 1370, in _process_data\n",
            "    data.reraise()\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/_utils.py\", line 706, in reraise\n",
            "    raise exception\n",
            "OSError: Caught OSError in DataLoader worker process 0.\n",
            "Original Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/_utils/worker.py\", line 309, in _worker_loop\n",
            "    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]\n",
            "           ^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/_utils/fetch.py\", line 52, in fetch\n",
            "    data = [self.dataset[idx] for idx in possibly_batched_index]\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/_utils/fetch.py\", line 52, in <listcomp>\n",
            "    data = [self.dataset[idx] for idx in possibly_batched_index]\n",
            "            ~~~~~~~~~~~~^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libdata.py\", line 333, in __getitem__\n",
            "    cg = self.pdb_to_cg(self.pdb_fn)\n",
            "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libdata.py\", line 313, in pdb_to_cg\n",
            "    return self.cg_model(\n",
            "           ^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libcg.py\", line 248, in __init__\n",
            "    super().__init__(pdb_fn, dcd_fn, **kwarg)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libcg.py\", line 44, in __init__\n",
            "    super().__init__(pdb_fn, dcd_fn, is_all=is_all, **kwarg)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libpdb.py\", line 20, in __init__\n",
            "    pdb = mdtraj.load(pdb_fn, standard_names=False)\n",
            "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 396, in load\n",
            "    kwargs[\"top\"] = _parse_topology(\n",
            "                    ^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 170, in _parse_topology\n",
            "    _traj = load_frame(top, 0, **kwargs)\n",
            "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 309, in load_frame\n",
            "    _assert_files_exist(filename)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 108, in _assert_files_exist\n",
            "    raise OSError(\"No such file: %s\" % fn)\n",
            "OSError: No such file: PED00082_C24_S00_GT.pdb\n",
            "\n",
            "\n",
            "STDOUT: \n",
            "Processing: PED00082_C16_S00_GT.pdb -> /content/drive/MyDrive/clustered_ensemble_outputs/PED00082_C16_S00_GT.all.pdb\n",
            "处理 PED00082_C16_S00_GT.pdb 时出错:\n",
            "返回码: 1\n",
            "STDERR: Traceback (most recent call last):\n",
            "  File \"/usr/local/bin/convert_cg2all\", line 8, in <module>\n",
            "    sys.exit(main())\n",
            "             ^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/script/convert_cg2all.py\", line 190, in main\n",
            "    batch = next(iter(input_s)).to(device)\n",
            "            ^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py\", line 630, in __next__\n",
            "    data = self._next_data()\n",
            "           ^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py\", line 1344, in _next_data\n",
            "    return self._process_data(data)\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py\", line 1370, in _process_data\n",
            "    data.reraise()\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/_utils.py\", line 706, in reraise\n",
            "    raise exception\n",
            "OSError: Caught OSError in DataLoader worker process 0.\n",
            "Original Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/_utils/worker.py\", line 309, in _worker_loop\n",
            "    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]\n",
            "           ^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/_utils/fetch.py\", line 52, in fetch\n",
            "    data = [self.dataset[idx] for idx in possibly_batched_index]\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/_utils/fetch.py\", line 52, in <listcomp>\n",
            "    data = [self.dataset[idx] for idx in possibly_batched_index]\n",
            "            ~~~~~~~~~~~~^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libdata.py\", line 333, in __getitem__\n",
            "    cg = self.pdb_to_cg(self.pdb_fn)\n",
            "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libdata.py\", line 313, in pdb_to_cg\n",
            "    return self.cg_model(\n",
            "           ^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libcg.py\", line 248, in __init__\n",
            "    super().__init__(pdb_fn, dcd_fn, **kwarg)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libcg.py\", line 44, in __init__\n",
            "    super().__init__(pdb_fn, dcd_fn, is_all=is_all, **kwarg)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libpdb.py\", line 20, in __init__\n",
            "    pdb = mdtraj.load(pdb_fn, standard_names=False)\n",
            "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 396, in load\n",
            "    kwargs[\"top\"] = _parse_topology(\n",
            "                    ^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 170, in _parse_topology\n",
            "    _traj = load_frame(top, 0, **kwargs)\n",
            "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 309, in load_frame\n",
            "    _assert_files_exist(filename)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 108, in _assert_files_exist\n",
            "    raise OSError(\"No such file: %s\" % fn)\n",
            "OSError: No such file: PED00082_C16_S00_GT.pdb\n",
            "\n",
            "\n",
            "STDOUT: \n",
            "Processing: PED00082_C05_S00_GT.pdb -> /content/drive/MyDrive/clustered_ensemble_outputs/PED00082_C05_S00_GT.all.pdb\n",
            "处理 PED00082_C05_S00_GT.pdb 时出错:\n",
            "返回码: 1\n",
            "STDERR: Traceback (most recent call last):\n",
            "  File \"/usr/local/bin/convert_cg2all\", line 8, in <module>\n",
            "    sys.exit(main())\n",
            "             ^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/script/convert_cg2all.py\", line 190, in main\n",
            "    batch = next(iter(input_s)).to(device)\n",
            "            ^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py\", line 630, in __next__\n",
            "    data = self._next_data()\n",
            "           ^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py\", line 1344, in _next_data\n",
            "    return self._process_data(data)\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py\", line 1370, in _process_data\n",
            "    data.reraise()\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/_utils.py\", line 706, in reraise\n",
            "    raise exception\n",
            "OSError: Caught OSError in DataLoader worker process 0.\n",
            "Original Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/_utils/worker.py\", line 309, in _worker_loop\n",
            "    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]\n",
            "           ^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/_utils/fetch.py\", line 52, in fetch\n",
            "    data = [self.dataset[idx] for idx in possibly_batched_index]\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/_utils/fetch.py\", line 52, in <listcomp>\n",
            "    data = [self.dataset[idx] for idx in possibly_batched_index]\n",
            "            ~~~~~~~~~~~~^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libdata.py\", line 333, in __getitem__\n",
            "    cg = self.pdb_to_cg(self.pdb_fn)\n",
            "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libdata.py\", line 313, in pdb_to_cg\n",
            "    return self.cg_model(\n",
            "           ^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libcg.py\", line 248, in __init__\n",
            "    super().__init__(pdb_fn, dcd_fn, **kwarg)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libcg.py\", line 44, in __init__\n",
            "    super().__init__(pdb_fn, dcd_fn, is_all=is_all, **kwarg)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libpdb.py\", line 20, in __init__\n",
            "    pdb = mdtraj.load(pdb_fn, standard_names=False)\n",
            "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 396, in load\n",
            "    kwargs[\"top\"] = _parse_topology(\n",
            "                    ^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 170, in _parse_topology\n",
            "    _traj = load_frame(top, 0, **kwargs)\n",
            "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 309, in load_frame\n",
            "    _assert_files_exist(filename)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 108, in _assert_files_exist\n",
            "    raise OSError(\"No such file: %s\" % fn)\n",
            "OSError: No such file: PED00082_C05_S00_GT.pdb\n",
            "\n",
            "\n",
            "STDOUT: \n",
            "Processing: PED00082_C02_S00_GT.pdb -> /content/drive/MyDrive/clustered_ensemble_outputs/PED00082_C02_S00_GT.all.pdb\n",
            "处理 PED00082_C02_S00_GT.pdb 时出错:\n",
            "返回码: 1\n",
            "STDERR: Traceback (most recent call last):\n",
            "  File \"/usr/local/bin/convert_cg2all\", line 8, in <module>\n",
            "    sys.exit(main())\n",
            "             ^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/script/convert_cg2all.py\", line 190, in main\n",
            "    batch = next(iter(input_s)).to(device)\n",
            "            ^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py\", line 630, in __next__\n",
            "    data = self._next_data()\n",
            "           ^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py\", line 1344, in _next_data\n",
            "    return self._process_data(data)\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py\", line 1370, in _process_data\n",
            "    data.reraise()\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/_utils.py\", line 706, in reraise\n",
            "    raise exception\n",
            "OSError: Caught OSError in DataLoader worker process 0.\n",
            "Original Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/_utils/worker.py\", line 309, in _worker_loop\n",
            "    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]\n",
            "           ^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/_utils/fetch.py\", line 52, in fetch\n",
            "    data = [self.dataset[idx] for idx in possibly_batched_index]\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/_utils/fetch.py\", line 52, in <listcomp>\n",
            "    data = [self.dataset[idx] for idx in possibly_batched_index]\n",
            "            ~~~~~~~~~~~~^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libdata.py\", line 333, in __getitem__\n",
            "    cg = self.pdb_to_cg(self.pdb_fn)\n",
            "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libdata.py\", line 313, in pdb_to_cg\n",
            "    return self.cg_model(\n",
            "           ^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libcg.py\", line 248, in __init__\n",
            "    super().__init__(pdb_fn, dcd_fn, **kwarg)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libcg.py\", line 44, in __init__\n",
            "    super().__init__(pdb_fn, dcd_fn, is_all=is_all, **kwarg)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libpdb.py\", line 20, in __init__\n",
            "    pdb = mdtraj.load(pdb_fn, standard_names=False)\n",
            "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 396, in load\n",
            "    kwargs[\"top\"] = _parse_topology(\n",
            "                    ^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 170, in _parse_topology\n",
            "    _traj = load_frame(top, 0, **kwargs)\n",
            "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 309, in load_frame\n",
            "    _assert_files_exist(filename)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 108, in _assert_files_exist\n",
            "    raise OSError(\"No such file: %s\" % fn)\n",
            "OSError: No such file: PED00082_C02_S00_GT.pdb\n",
            "\n",
            "\n",
            "STDOUT: \n",
            "Processing: PED00082_C09_S00_GT.pdb -> /content/drive/MyDrive/clustered_ensemble_outputs/PED00082_C09_S00_GT.all.pdb\n",
            "处理 PED00082_C09_S00_GT.pdb 时出错:\n",
            "返回码: 1\n",
            "STDERR: Traceback (most recent call last):\n",
            "  File \"/usr/local/bin/convert_cg2all\", line 8, in <module>\n",
            "    sys.exit(main())\n",
            "             ^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/script/convert_cg2all.py\", line 190, in main\n",
            "    batch = next(iter(input_s)).to(device)\n",
            "            ^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py\", line 630, in __next__\n",
            "    data = self._next_data()\n",
            "           ^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py\", line 1344, in _next_data\n",
            "    return self._process_data(data)\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py\", line 1370, in _process_data\n",
            "    data.reraise()\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/_utils.py\", line 706, in reraise\n",
            "    raise exception\n",
            "OSError: Caught OSError in DataLoader worker process 0.\n",
            "Original Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/_utils/worker.py\", line 309, in _worker_loop\n",
            "    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]\n",
            "           ^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/_utils/fetch.py\", line 52, in fetch\n",
            "    data = [self.dataset[idx] for idx in possibly_batched_index]\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/_utils/fetch.py\", line 52, in <listcomp>\n",
            "    data = [self.dataset[idx] for idx in possibly_batched_index]\n",
            "            ~~~~~~~~~~~~^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libdata.py\", line 333, in __getitem__\n",
            "    cg = self.pdb_to_cg(self.pdb_fn)\n",
            "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libdata.py\", line 313, in pdb_to_cg\n",
            "    return self.cg_model(\n",
            "           ^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libcg.py\", line 248, in __init__\n",
            "    super().__init__(pdb_fn, dcd_fn, **kwarg)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libcg.py\", line 44, in __init__\n",
            "    super().__init__(pdb_fn, dcd_fn, is_all=is_all, **kwarg)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libpdb.py\", line 20, in __init__\n",
            "    pdb = mdtraj.load(pdb_fn, standard_names=False)\n",
            "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 396, in load\n",
            "    kwargs[\"top\"] = _parse_topology(\n",
            "                    ^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 170, in _parse_topology\n",
            "    _traj = load_frame(top, 0, **kwargs)\n",
            "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 309, in load_frame\n",
            "    _assert_files_exist(filename)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 108, in _assert_files_exist\n",
            "    raise OSError(\"No such file: %s\" % fn)\n",
            "OSError: No such file: PED00082_C09_S00_GT.pdb\n",
            "\n",
            "\n",
            "STDOUT: \n",
            "Processing: PED00082_C01_S00_GT.pdb -> /content/drive/MyDrive/clustered_ensemble_outputs/PED00082_C01_S00_GT.all.pdb\n",
            "处理 PED00082_C01_S00_GT.pdb 时出错:\n",
            "返回码: 1\n",
            "STDERR: Traceback (most recent call last):\n",
            "  File \"/usr/local/bin/convert_cg2all\", line 8, in <module>\n",
            "    sys.exit(main())\n",
            "             ^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/script/convert_cg2all.py\", line 190, in main\n",
            "    batch = next(iter(input_s)).to(device)\n",
            "            ^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py\", line 630, in __next__\n",
            "    data = self._next_data()\n",
            "           ^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py\", line 1344, in _next_data\n",
            "    return self._process_data(data)\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py\", line 1370, in _process_data\n",
            "    data.reraise()\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/_utils.py\", line 706, in reraise\n",
            "    raise exception\n",
            "OSError: Caught OSError in DataLoader worker process 0.\n",
            "Original Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/_utils/worker.py\", line 309, in _worker_loop\n",
            "    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]\n",
            "           ^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/_utils/fetch.py\", line 52, in fetch\n",
            "    data = [self.dataset[idx] for idx in possibly_batched_index]\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/_utils/fetch.py\", line 52, in <listcomp>\n",
            "    data = [self.dataset[idx] for idx in possibly_batched_index]\n",
            "            ~~~~~~~~~~~~^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libdata.py\", line 333, in __getitem__\n",
            "    cg = self.pdb_to_cg(self.pdb_fn)\n",
            "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libdata.py\", line 313, in pdb_to_cg\n",
            "    return self.cg_model(\n",
            "           ^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libcg.py\", line 248, in __init__\n",
            "    super().__init__(pdb_fn, dcd_fn, **kwarg)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libcg.py\", line 44, in __init__\n",
            "    super().__init__(pdb_fn, dcd_fn, is_all=is_all, **kwarg)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libpdb.py\", line 20, in __init__\n",
            "    pdb = mdtraj.load(pdb_fn, standard_names=False)\n",
            "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 396, in load\n",
            "    kwargs[\"top\"] = _parse_topology(\n",
            "                    ^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 170, in _parse_topology\n",
            "    _traj = load_frame(top, 0, **kwargs)\n",
            "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 309, in load_frame\n",
            "    _assert_files_exist(filename)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 108, in _assert_files_exist\n",
            "    raise OSError(\"No such file: %s\" % fn)\n",
            "OSError: No such file: PED00082_C01_S00_GT.pdb\n",
            "\n",
            "\n",
            "STDOUT: \n",
            "Processing: PED00082_C04_S00_GT.pdb -> /content/drive/MyDrive/clustered_ensemble_outputs/PED00082_C04_S00_GT.all.pdb\n",
            "处理 PED00082_C04_S00_GT.pdb 时出错:\n",
            "返回码: 1\n",
            "STDERR: Traceback (most recent call last):\n",
            "  File \"/usr/local/bin/convert_cg2all\", line 8, in <module>\n",
            "    sys.exit(main())\n",
            "             ^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/script/convert_cg2all.py\", line 190, in main\n",
            "    batch = next(iter(input_s)).to(device)\n",
            "            ^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py\", line 630, in __next__\n",
            "    data = self._next_data()\n",
            "           ^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py\", line 1344, in _next_data\n",
            "    return self._process_data(data)\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py\", line 1370, in _process_data\n",
            "    data.reraise()\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/_utils.py\", line 706, in reraise\n",
            "    raise exception\n",
            "OSError: Caught OSError in DataLoader worker process 0.\n",
            "Original Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/_utils/worker.py\", line 309, in _worker_loop\n",
            "    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]\n",
            "           ^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/_utils/fetch.py\", line 52, in fetch\n",
            "    data = [self.dataset[idx] for idx in possibly_batched_index]\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/_utils/fetch.py\", line 52, in <listcomp>\n",
            "    data = [self.dataset[idx] for idx in possibly_batched_index]\n",
            "            ~~~~~~~~~~~~^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libdata.py\", line 333, in __getitem__\n",
            "    cg = self.pdb_to_cg(self.pdb_fn)\n",
            "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libdata.py\", line 313, in pdb_to_cg\n",
            "    return self.cg_model(\n",
            "           ^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libcg.py\", line 248, in __init__\n",
            "    super().__init__(pdb_fn, dcd_fn, **kwarg)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libcg.py\", line 44, in __init__\n",
            "    super().__init__(pdb_fn, dcd_fn, is_all=is_all, **kwarg)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libpdb.py\", line 20, in __init__\n",
            "    pdb = mdtraj.load(pdb_fn, standard_names=False)\n",
            "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 396, in load\n",
            "    kwargs[\"top\"] = _parse_topology(\n",
            "                    ^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 170, in _parse_topology\n",
            "    _traj = load_frame(top, 0, **kwargs)\n",
            "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 309, in load_frame\n",
            "    _assert_files_exist(filename)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 108, in _assert_files_exist\n",
            "    raise OSError(\"No such file: %s\" % fn)\n",
            "OSError: No such file: PED00082_C04_S00_GT.pdb\n",
            "\n",
            "\n",
            "STDOUT: \n",
            "Processing: PED00082_C00_S00_GT.pdb -> /content/drive/MyDrive/clustered_ensemble_outputs/PED00082_C00_S00_GT.all.pdb\n",
            "处理 PED00082_C00_S00_GT.pdb 时出错:\n",
            "返回码: 1\n",
            "STDERR: Traceback (most recent call last):\n",
            "  File \"/usr/local/bin/convert_cg2all\", line 8, in <module>\n",
            "    sys.exit(main())\n",
            "             ^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/script/convert_cg2all.py\", line 190, in main\n",
            "    batch = next(iter(input_s)).to(device)\n",
            "            ^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py\", line 630, in __next__\n",
            "    data = self._next_data()\n",
            "           ^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py\", line 1344, in _next_data\n",
            "    return self._process_data(data)\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py\", line 1370, in _process_data\n",
            "    data.reraise()\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/_utils.py\", line 706, in reraise\n",
            "    raise exception\n",
            "OSError: Caught OSError in DataLoader worker process 0.\n",
            "Original Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/_utils/worker.py\", line 309, in _worker_loop\n",
            "    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]\n",
            "           ^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/_utils/fetch.py\", line 52, in fetch\n",
            "    data = [self.dataset[idx] for idx in possibly_batched_index]\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/_utils/fetch.py\", line 52, in <listcomp>\n",
            "    data = [self.dataset[idx] for idx in possibly_batched_index]\n",
            "            ~~~~~~~~~~~~^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libdata.py\", line 333, in __getitem__\n",
            "    cg = self.pdb_to_cg(self.pdb_fn)\n",
            "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libdata.py\", line 313, in pdb_to_cg\n",
            "    return self.cg_model(\n",
            "           ^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libcg.py\", line 248, in __init__\n",
            "    super().__init__(pdb_fn, dcd_fn, **kwarg)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libcg.py\", line 44, in __init__\n",
            "    super().__init__(pdb_fn, dcd_fn, is_all=is_all, **kwarg)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libpdb.py\", line 20, in __init__\n",
            "    pdb = mdtraj.load(pdb_fn, standard_names=False)\n",
            "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 396, in load\n",
            "    kwargs[\"top\"] = _parse_topology(\n",
            "                    ^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 170, in _parse_topology\n",
            "    _traj = load_frame(top, 0, **kwargs)\n",
            "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 309, in load_frame\n",
            "    _assert_files_exist(filename)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 108, in _assert_files_exist\n",
            "    raise OSError(\"No such file: %s\" % fn)\n",
            "OSError: No such file: PED00082_C00_S00_GT.pdb\n",
            "\n",
            "\n",
            "STDOUT: \n",
            "Processing: PED00082_C23_S00_GT.pdb -> /content/drive/MyDrive/clustered_ensemble_outputs/PED00082_C23_S00_GT.all.pdb\n",
            "处理 PED00082_C23_S00_GT.pdb 时出错:\n",
            "返回码: 1\n",
            "STDERR: Traceback (most recent call last):\n",
            "  File \"/usr/local/bin/convert_cg2all\", line 8, in <module>\n",
            "    sys.exit(main())\n",
            "             ^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/script/convert_cg2all.py\", line 190, in main\n",
            "    batch = next(iter(input_s)).to(device)\n",
            "            ^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py\", line 630, in __next__\n",
            "    data = self._next_data()\n",
            "           ^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py\", line 1344, in _next_data\n",
            "    return self._process_data(data)\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py\", line 1370, in _process_data\n",
            "    data.reraise()\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/_utils.py\", line 706, in reraise\n",
            "    raise exception\n",
            "OSError: Caught OSError in DataLoader worker process 0.\n",
            "Original Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/_utils/worker.py\", line 309, in _worker_loop\n",
            "    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]\n",
            "           ^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/_utils/fetch.py\", line 52, in fetch\n",
            "    data = [self.dataset[idx] for idx in possibly_batched_index]\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/_utils/fetch.py\", line 52, in <listcomp>\n",
            "    data = [self.dataset[idx] for idx in possibly_batched_index]\n",
            "            ~~~~~~~~~~~~^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libdata.py\", line 333, in __getitem__\n",
            "    cg = self.pdb_to_cg(self.pdb_fn)\n",
            "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libdata.py\", line 313, in pdb_to_cg\n",
            "    return self.cg_model(\n",
            "           ^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libcg.py\", line 248, in __init__\n",
            "    super().__init__(pdb_fn, dcd_fn, **kwarg)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libcg.py\", line 44, in __init__\n",
            "    super().__init__(pdb_fn, dcd_fn, is_all=is_all, **kwarg)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libpdb.py\", line 20, in __init__\n",
            "    pdb = mdtraj.load(pdb_fn, standard_names=False)\n",
            "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 396, in load\n",
            "    kwargs[\"top\"] = _parse_topology(\n",
            "                    ^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 170, in _parse_topology\n",
            "    _traj = load_frame(top, 0, **kwargs)\n",
            "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 309, in load_frame\n",
            "    _assert_files_exist(filename)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 108, in _assert_files_exist\n",
            "    raise OSError(\"No such file: %s\" % fn)\n",
            "OSError: No such file: PED00082_C23_S00_GT.pdb\n",
            "\n",
            "\n",
            "STDOUT: \n",
            "Processing: PED00082_C15_S00_GT.pdb -> /content/drive/MyDrive/clustered_ensemble_outputs/PED00082_C15_S00_GT.all.pdb\n",
            "处理 PED00082_C15_S00_GT.pdb 时出错:\n",
            "返回码: 1\n",
            "STDERR: Traceback (most recent call last):\n",
            "  File \"/usr/local/bin/convert_cg2all\", line 8, in <module>\n",
            "    sys.exit(main())\n",
            "             ^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/script/convert_cg2all.py\", line 190, in main\n",
            "    batch = next(iter(input_s)).to(device)\n",
            "            ^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py\", line 630, in __next__\n",
            "    data = self._next_data()\n",
            "           ^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py\", line 1344, in _next_data\n",
            "    return self._process_data(data)\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py\", line 1370, in _process_data\n",
            "    data.reraise()\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/_utils.py\", line 706, in reraise\n",
            "    raise exception\n",
            "OSError: Caught OSError in DataLoader worker process 0.\n",
            "Original Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/_utils/worker.py\", line 309, in _worker_loop\n",
            "    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]\n",
            "           ^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/_utils/fetch.py\", line 52, in fetch\n",
            "    data = [self.dataset[idx] for idx in possibly_batched_index]\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/_utils/fetch.py\", line 52, in <listcomp>\n",
            "    data = [self.dataset[idx] for idx in possibly_batched_index]\n",
            "            ~~~~~~~~~~~~^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libdata.py\", line 333, in __getitem__\n",
            "    cg = self.pdb_to_cg(self.pdb_fn)\n",
            "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libdata.py\", line 313, in pdb_to_cg\n",
            "    return self.cg_model(\n",
            "           ^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libcg.py\", line 248, in __init__\n",
            "    super().__init__(pdb_fn, dcd_fn, **kwarg)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libcg.py\", line 44, in __init__\n",
            "    super().__init__(pdb_fn, dcd_fn, is_all=is_all, **kwarg)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libpdb.py\", line 20, in __init__\n",
            "    pdb = mdtraj.load(pdb_fn, standard_names=False)\n",
            "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 396, in load\n",
            "    kwargs[\"top\"] = _parse_topology(\n",
            "                    ^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 170, in _parse_topology\n",
            "    _traj = load_frame(top, 0, **kwargs)\n",
            "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 309, in load_frame\n",
            "    _assert_files_exist(filename)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 108, in _assert_files_exist\n",
            "    raise OSError(\"No such file: %s\" % fn)\n",
            "OSError: No such file: PED00082_C15_S00_GT.pdb\n",
            "\n",
            "\n",
            "STDOUT: \n",
            "Processing: PED00082_C18_S00_GT.pdb -> /content/drive/MyDrive/clustered_ensemble_outputs/PED00082_C18_S00_GT.all.pdb\n",
            "处理 PED00082_C18_S00_GT.pdb 时出错:\n",
            "返回码: 1\n",
            "STDERR: Traceback (most recent call last):\n",
            "  File \"/usr/local/bin/convert_cg2all\", line 8, in <module>\n",
            "    sys.exit(main())\n",
            "             ^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/script/convert_cg2all.py\", line 190, in main\n",
            "    batch = next(iter(input_s)).to(device)\n",
            "            ^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py\", line 630, in __next__\n",
            "    data = self._next_data()\n",
            "           ^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py\", line 1344, in _next_data\n",
            "    return self._process_data(data)\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py\", line 1370, in _process_data\n",
            "    data.reraise()\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/_utils.py\", line 706, in reraise\n",
            "    raise exception\n",
            "OSError: Caught OSError in DataLoader worker process 0.\n",
            "Original Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/_utils/worker.py\", line 309, in _worker_loop\n",
            "    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]\n",
            "           ^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/_utils/fetch.py\", line 52, in fetch\n",
            "    data = [self.dataset[idx] for idx in possibly_batched_index]\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/_utils/fetch.py\", line 52, in <listcomp>\n",
            "    data = [self.dataset[idx] for idx in possibly_batched_index]\n",
            "            ~~~~~~~~~~~~^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libdata.py\", line 333, in __getitem__\n",
            "    cg = self.pdb_to_cg(self.pdb_fn)\n",
            "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libdata.py\", line 313, in pdb_to_cg\n",
            "    return self.cg_model(\n",
            "           ^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libcg.py\", line 248, in __init__\n",
            "    super().__init__(pdb_fn, dcd_fn, **kwarg)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libcg.py\", line 44, in __init__\n",
            "    super().__init__(pdb_fn, dcd_fn, is_all=is_all, **kwarg)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libpdb.py\", line 20, in __init__\n",
            "    pdb = mdtraj.load(pdb_fn, standard_names=False)\n",
            "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 396, in load\n",
            "    kwargs[\"top\"] = _parse_topology(\n",
            "                    ^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 170, in _parse_topology\n",
            "    _traj = load_frame(top, 0, **kwargs)\n",
            "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 309, in load_frame\n",
            "    _assert_files_exist(filename)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 108, in _assert_files_exist\n",
            "    raise OSError(\"No such file: %s\" % fn)\n",
            "OSError: No such file: PED00082_C18_S00_GT.pdb\n",
            "\n",
            "\n",
            "STDOUT: \n",
            "Processing: PED00082_C07_S00_GT.pdb -> /content/drive/MyDrive/clustered_ensemble_outputs/PED00082_C07_S00_GT.all.pdb\n",
            "处理 PED00082_C07_S00_GT.pdb 时出错:\n",
            "返回码: 1\n",
            "STDERR: Traceback (most recent call last):\n",
            "  File \"/usr/local/bin/convert_cg2all\", line 8, in <module>\n",
            "    sys.exit(main())\n",
            "             ^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/script/convert_cg2all.py\", line 190, in main\n",
            "    batch = next(iter(input_s)).to(device)\n",
            "            ^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py\", line 630, in __next__\n",
            "    data = self._next_data()\n",
            "           ^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py\", line 1344, in _next_data\n",
            "    return self._process_data(data)\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py\", line 1370, in _process_data\n",
            "    data.reraise()\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/_utils.py\", line 706, in reraise\n",
            "    raise exception\n",
            "OSError: Caught OSError in DataLoader worker process 0.\n",
            "Original Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/_utils/worker.py\", line 309, in _worker_loop\n",
            "    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]\n",
            "           ^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/_utils/fetch.py\", line 52, in fetch\n",
            "    data = [self.dataset[idx] for idx in possibly_batched_index]\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/_utils/fetch.py\", line 52, in <listcomp>\n",
            "    data = [self.dataset[idx] for idx in possibly_batched_index]\n",
            "            ~~~~~~~~~~~~^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libdata.py\", line 333, in __getitem__\n",
            "    cg = self.pdb_to_cg(self.pdb_fn)\n",
            "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libdata.py\", line 313, in pdb_to_cg\n",
            "    return self.cg_model(\n",
            "           ^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libcg.py\", line 248, in __init__\n",
            "    super().__init__(pdb_fn, dcd_fn, **kwarg)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libcg.py\", line 44, in __init__\n",
            "    super().__init__(pdb_fn, dcd_fn, is_all=is_all, **kwarg)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libpdb.py\", line 20, in __init__\n",
            "    pdb = mdtraj.load(pdb_fn, standard_names=False)\n",
            "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 396, in load\n",
            "    kwargs[\"top\"] = _parse_topology(\n",
            "                    ^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 170, in _parse_topology\n",
            "    _traj = load_frame(top, 0, **kwargs)\n",
            "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 309, in load_frame\n",
            "    _assert_files_exist(filename)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 108, in _assert_files_exist\n",
            "    raise OSError(\"No such file: %s\" % fn)\n",
            "OSError: No such file: PED00082_C07_S00_GT.pdb\n",
            "\n",
            "\n",
            "STDOUT: \n",
            "Processing: PED00082_C03_S00_GT.pdb -> /content/drive/MyDrive/clustered_ensemble_outputs/PED00082_C03_S00_GT.all.pdb\n",
            "处理 PED00082_C03_S00_GT.pdb 时出错:\n",
            "返回码: 1\n",
            "STDERR: Traceback (most recent call last):\n",
            "  File \"/usr/local/bin/convert_cg2all\", line 8, in <module>\n",
            "    sys.exit(main())\n",
            "             ^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/script/convert_cg2all.py\", line 190, in main\n",
            "    batch = next(iter(input_s)).to(device)\n",
            "            ^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py\", line 630, in __next__\n",
            "    data = self._next_data()\n",
            "           ^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py\", line 1344, in _next_data\n",
            "    return self._process_data(data)\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py\", line 1370, in _process_data\n",
            "    data.reraise()\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/_utils.py\", line 706, in reraise\n",
            "    raise exception\n",
            "OSError: Caught OSError in DataLoader worker process 0.\n",
            "Original Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/_utils/worker.py\", line 309, in _worker_loop\n",
            "    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]\n",
            "           ^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/_utils/fetch.py\", line 52, in fetch\n",
            "    data = [self.dataset[idx] for idx in possibly_batched_index]\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/_utils/fetch.py\", line 52, in <listcomp>\n",
            "    data = [self.dataset[idx] for idx in possibly_batched_index]\n",
            "            ~~~~~~~~~~~~^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libdata.py\", line 333, in __getitem__\n",
            "    cg = self.pdb_to_cg(self.pdb_fn)\n",
            "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libdata.py\", line 313, in pdb_to_cg\n",
            "    return self.cg_model(\n",
            "           ^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libcg.py\", line 248, in __init__\n",
            "    super().__init__(pdb_fn, dcd_fn, **kwarg)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libcg.py\", line 44, in __init__\n",
            "    super().__init__(pdb_fn, dcd_fn, is_all=is_all, **kwarg)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libpdb.py\", line 20, in __init__\n",
            "    pdb = mdtraj.load(pdb_fn, standard_names=False)\n",
            "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 396, in load\n",
            "    kwargs[\"top\"] = _parse_topology(\n",
            "                    ^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 170, in _parse_topology\n",
            "    _traj = load_frame(top, 0, **kwargs)\n",
            "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 309, in load_frame\n",
            "    _assert_files_exist(filename)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 108, in _assert_files_exist\n",
            "    raise OSError(\"No such file: %s\" % fn)\n",
            "OSError: No such file: PED00082_C03_S00_GT.pdb\n",
            "\n",
            "\n",
            "STDOUT: \n",
            "Processing: PED00082_C08_S00_GT.pdb -> /content/drive/MyDrive/clustered_ensemble_outputs/PED00082_C08_S00_GT.all.pdb\n",
            "处理 PED00082_C08_S00_GT.pdb 时出错:\n",
            "返回码: 1\n",
            "STDERR: Traceback (most recent call last):\n",
            "  File \"/usr/local/bin/convert_cg2all\", line 8, in <module>\n",
            "    sys.exit(main())\n",
            "             ^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/script/convert_cg2all.py\", line 190, in main\n",
            "    batch = next(iter(input_s)).to(device)\n",
            "            ^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py\", line 630, in __next__\n",
            "    data = self._next_data()\n",
            "           ^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py\", line 1344, in _next_data\n",
            "    return self._process_data(data)\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py\", line 1370, in _process_data\n",
            "    data.reraise()\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/_utils.py\", line 706, in reraise\n",
            "    raise exception\n",
            "OSError: Caught OSError in DataLoader worker process 0.\n",
            "Original Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/_utils/worker.py\", line 309, in _worker_loop\n",
            "    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]\n",
            "           ^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/_utils/fetch.py\", line 52, in fetch\n",
            "    data = [self.dataset[idx] for idx in possibly_batched_index]\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/_utils/fetch.py\", line 52, in <listcomp>\n",
            "    data = [self.dataset[idx] for idx in possibly_batched_index]\n",
            "            ~~~~~~~~~~~~^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libdata.py\", line 333, in __getitem__\n",
            "    cg = self.pdb_to_cg(self.pdb_fn)\n",
            "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libdata.py\", line 313, in pdb_to_cg\n",
            "    return self.cg_model(\n",
            "           ^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libcg.py\", line 248, in __init__\n",
            "    super().__init__(pdb_fn, dcd_fn, **kwarg)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libcg.py\", line 44, in __init__\n",
            "    super().__init__(pdb_fn, dcd_fn, is_all=is_all, **kwarg)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libpdb.py\", line 20, in __init__\n",
            "    pdb = mdtraj.load(pdb_fn, standard_names=False)\n",
            "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 396, in load\n",
            "    kwargs[\"top\"] = _parse_topology(\n",
            "                    ^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 170, in _parse_topology\n",
            "    _traj = load_frame(top, 0, **kwargs)\n",
            "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 309, in load_frame\n",
            "    _assert_files_exist(filename)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 108, in _assert_files_exist\n",
            "    raise OSError(\"No such file: %s\" % fn)\n",
            "OSError: No such file: PED00082_C08_S00_GT.pdb\n",
            "\n",
            "\n",
            "STDOUT: \n",
            "Processing: PED00082_C13_S00_GT.pdb -> /content/drive/MyDrive/clustered_ensemble_outputs/PED00082_C13_S00_GT.all.pdb\n",
            "处理 PED00082_C13_S00_GT.pdb 时出错:\n",
            "返回码: 1\n",
            "STDERR: Traceback (most recent call last):\n",
            "  File \"/usr/local/bin/convert_cg2all\", line 8, in <module>\n",
            "    sys.exit(main())\n",
            "             ^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/script/convert_cg2all.py\", line 190, in main\n",
            "    batch = next(iter(input_s)).to(device)\n",
            "            ^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py\", line 630, in __next__\n",
            "    data = self._next_data()\n",
            "           ^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py\", line 1344, in _next_data\n",
            "    return self._process_data(data)\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py\", line 1370, in _process_data\n",
            "    data.reraise()\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/_utils.py\", line 706, in reraise\n",
            "    raise exception\n",
            "OSError: Caught OSError in DataLoader worker process 0.\n",
            "Original Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/_utils/worker.py\", line 309, in _worker_loop\n",
            "    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]\n",
            "           ^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/_utils/fetch.py\", line 52, in fetch\n",
            "    data = [self.dataset[idx] for idx in possibly_batched_index]\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/_utils/fetch.py\", line 52, in <listcomp>\n",
            "    data = [self.dataset[idx] for idx in possibly_batched_index]\n",
            "            ~~~~~~~~~~~~^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libdata.py\", line 333, in __getitem__\n",
            "    cg = self.pdb_to_cg(self.pdb_fn)\n",
            "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libdata.py\", line 313, in pdb_to_cg\n",
            "    return self.cg_model(\n",
            "           ^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libcg.py\", line 248, in __init__\n",
            "    super().__init__(pdb_fn, dcd_fn, **kwarg)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libcg.py\", line 44, in __init__\n",
            "    super().__init__(pdb_fn, dcd_fn, is_all=is_all, **kwarg)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libpdb.py\", line 20, in __init__\n",
            "    pdb = mdtraj.load(pdb_fn, standard_names=False)\n",
            "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 396, in load\n",
            "    kwargs[\"top\"] = _parse_topology(\n",
            "                    ^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 170, in _parse_topology\n",
            "    _traj = load_frame(top, 0, **kwargs)\n",
            "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 309, in load_frame\n",
            "    _assert_files_exist(filename)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 108, in _assert_files_exist\n",
            "    raise OSError(\"No such file: %s\" % fn)\n",
            "OSError: No such file: PED00082_C13_S00_GT.pdb\n",
            "\n",
            "\n",
            "STDOUT: \n",
            "Processing: PED00082_C22_S00_GT.pdb -> /content/drive/MyDrive/clustered_ensemble_outputs/PED00082_C22_S00_GT.all.pdb\n",
            "处理 PED00082_C22_S00_GT.pdb 时出错:\n",
            "返回码: 1\n",
            "STDERR: Traceback (most recent call last):\n",
            "  File \"/usr/local/bin/convert_cg2all\", line 8, in <module>\n",
            "    sys.exit(main())\n",
            "             ^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/script/convert_cg2all.py\", line 190, in main\n",
            "    batch = next(iter(input_s)).to(device)\n",
            "            ^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py\", line 630, in __next__\n",
            "    data = self._next_data()\n",
            "           ^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py\", line 1344, in _next_data\n",
            "    return self._process_data(data)\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py\", line 1370, in _process_data\n",
            "    data.reraise()\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/_utils.py\", line 706, in reraise\n",
            "    raise exception\n",
            "OSError: Caught OSError in DataLoader worker process 0.\n",
            "Original Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/_utils/worker.py\", line 309, in _worker_loop\n",
            "    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]\n",
            "           ^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/_utils/fetch.py\", line 52, in fetch\n",
            "    data = [self.dataset[idx] for idx in possibly_batched_index]\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/_utils/fetch.py\", line 52, in <listcomp>\n",
            "    data = [self.dataset[idx] for idx in possibly_batched_index]\n",
            "            ~~~~~~~~~~~~^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libdata.py\", line 333, in __getitem__\n",
            "    cg = self.pdb_to_cg(self.pdb_fn)\n",
            "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libdata.py\", line 313, in pdb_to_cg\n",
            "    return self.cg_model(\n",
            "           ^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libcg.py\", line 248, in __init__\n",
            "    super().__init__(pdb_fn, dcd_fn, **kwarg)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libcg.py\", line 44, in __init__\n",
            "    super().__init__(pdb_fn, dcd_fn, is_all=is_all, **kwarg)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libpdb.py\", line 20, in __init__\n",
            "    pdb = mdtraj.load(pdb_fn, standard_names=False)\n",
            "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 396, in load\n",
            "    kwargs[\"top\"] = _parse_topology(\n",
            "                    ^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 170, in _parse_topology\n",
            "    _traj = load_frame(top, 0, **kwargs)\n",
            "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 309, in load_frame\n",
            "    _assert_files_exist(filename)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 108, in _assert_files_exist\n",
            "    raise OSError(\"No such file: %s\" % fn)\n",
            "OSError: No such file: PED00082_C22_S00_GT.pdb\n",
            "\n",
            "\n",
            "STDOUT: \n",
            "Processing: PED00082_C11_S00_GT.pdb -> /content/drive/MyDrive/clustered_ensemble_outputs/PED00082_C11_S00_GT.all.pdb\n",
            "处理 PED00082_C11_S00_GT.pdb 时出错:\n",
            "返回码: 1\n",
            "STDERR: Traceback (most recent call last):\n",
            "  File \"/usr/local/bin/convert_cg2all\", line 8, in <module>\n",
            "    sys.exit(main())\n",
            "             ^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/script/convert_cg2all.py\", line 190, in main\n",
            "    batch = next(iter(input_s)).to(device)\n",
            "            ^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py\", line 630, in __next__\n",
            "    data = self._next_data()\n",
            "           ^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py\", line 1344, in _next_data\n",
            "    return self._process_data(data)\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py\", line 1370, in _process_data\n",
            "    data.reraise()\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/_utils.py\", line 706, in reraise\n",
            "    raise exception\n",
            "OSError: Caught OSError in DataLoader worker process 0.\n",
            "Original Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/_utils/worker.py\", line 309, in _worker_loop\n",
            "    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]\n",
            "           ^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/_utils/fetch.py\", line 52, in fetch\n",
            "    data = [self.dataset[idx] for idx in possibly_batched_index]\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/_utils/fetch.py\", line 52, in <listcomp>\n",
            "    data = [self.dataset[idx] for idx in possibly_batched_index]\n",
            "            ~~~~~~~~~~~~^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libdata.py\", line 333, in __getitem__\n",
            "    cg = self.pdb_to_cg(self.pdb_fn)\n",
            "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libdata.py\", line 313, in pdb_to_cg\n",
            "    return self.cg_model(\n",
            "           ^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libcg.py\", line 248, in __init__\n",
            "    super().__init__(pdb_fn, dcd_fn, **kwarg)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libcg.py\", line 44, in __init__\n",
            "    super().__init__(pdb_fn, dcd_fn, is_all=is_all, **kwarg)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libpdb.py\", line 20, in __init__\n",
            "    pdb = mdtraj.load(pdb_fn, standard_names=False)\n",
            "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 396, in load\n",
            "    kwargs[\"top\"] = _parse_topology(\n",
            "                    ^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 170, in _parse_topology\n",
            "    _traj = load_frame(top, 0, **kwargs)\n",
            "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 309, in load_frame\n",
            "    _assert_files_exist(filename)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 108, in _assert_files_exist\n",
            "    raise OSError(\"No such file: %s\" % fn)\n",
            "OSError: No such file: PED00082_C11_S00_GT.pdb\n",
            "\n",
            "\n",
            "STDOUT: \n",
            "Processing: PED00082_C19_S00_GT.pdb -> /content/drive/MyDrive/clustered_ensemble_outputs/PED00082_C19_S00_GT.all.pdb\n",
            "处理 PED00082_C19_S00_GT.pdb 时出错:\n",
            "返回码: 1\n",
            "STDERR: Traceback (most recent call last):\n",
            "  File \"/usr/local/bin/convert_cg2all\", line 8, in <module>\n",
            "    sys.exit(main())\n",
            "             ^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/script/convert_cg2all.py\", line 190, in main\n",
            "    batch = next(iter(input_s)).to(device)\n",
            "            ^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py\", line 630, in __next__\n",
            "    data = self._next_data()\n",
            "           ^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py\", line 1344, in _next_data\n",
            "    return self._process_data(data)\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py\", line 1370, in _process_data\n",
            "    data.reraise()\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/_utils.py\", line 706, in reraise\n",
            "    raise exception\n",
            "OSError: Caught OSError in DataLoader worker process 0.\n",
            "Original Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/_utils/worker.py\", line 309, in _worker_loop\n",
            "    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]\n",
            "           ^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/_utils/fetch.py\", line 52, in fetch\n",
            "    data = [self.dataset[idx] for idx in possibly_batched_index]\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/_utils/fetch.py\", line 52, in <listcomp>\n",
            "    data = [self.dataset[idx] for idx in possibly_batched_index]\n",
            "            ~~~~~~~~~~~~^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libdata.py\", line 333, in __getitem__\n",
            "    cg = self.pdb_to_cg(self.pdb_fn)\n",
            "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libdata.py\", line 313, in pdb_to_cg\n",
            "    return self.cg_model(\n",
            "           ^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libcg.py\", line 248, in __init__\n",
            "    super().__init__(pdb_fn, dcd_fn, **kwarg)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libcg.py\", line 44, in __init__\n",
            "    super().__init__(pdb_fn, dcd_fn, is_all=is_all, **kwarg)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libpdb.py\", line 20, in __init__\n",
            "    pdb = mdtraj.load(pdb_fn, standard_names=False)\n",
            "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 396, in load\n",
            "    kwargs[\"top\"] = _parse_topology(\n",
            "                    ^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 170, in _parse_topology\n",
            "    _traj = load_frame(top, 0, **kwargs)\n",
            "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 309, in load_frame\n",
            "    _assert_files_exist(filename)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 108, in _assert_files_exist\n",
            "    raise OSError(\"No such file: %s\" % fn)\n",
            "OSError: No such file: PED00082_C19_S00_GT.pdb\n",
            "\n",
            "\n",
            "STDOUT: \n",
            "Processing: PED00082_C14_S00_GT.pdb -> /content/drive/MyDrive/clustered_ensemble_outputs/PED00082_C14_S00_GT.all.pdb\n",
            "处理 PED00082_C14_S00_GT.pdb 时出错:\n",
            "返回码: 1\n",
            "STDERR: Traceback (most recent call last):\n",
            "  File \"/usr/local/bin/convert_cg2all\", line 8, in <module>\n",
            "    sys.exit(main())\n",
            "             ^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/script/convert_cg2all.py\", line 190, in main\n",
            "    batch = next(iter(input_s)).to(device)\n",
            "            ^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py\", line 630, in __next__\n",
            "    data = self._next_data()\n",
            "           ^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py\", line 1344, in _next_data\n",
            "    return self._process_data(data)\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py\", line 1370, in _process_data\n",
            "    data.reraise()\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/_utils.py\", line 706, in reraise\n",
            "    raise exception\n",
            "OSError: Caught OSError in DataLoader worker process 0.\n",
            "Original Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/_utils/worker.py\", line 309, in _worker_loop\n",
            "    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]\n",
            "           ^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/_utils/fetch.py\", line 52, in fetch\n",
            "    data = [self.dataset[idx] for idx in possibly_batched_index]\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/_utils/fetch.py\", line 52, in <listcomp>\n",
            "    data = [self.dataset[idx] for idx in possibly_batched_index]\n",
            "            ~~~~~~~~~~~~^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libdata.py\", line 333, in __getitem__\n",
            "    cg = self.pdb_to_cg(self.pdb_fn)\n",
            "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libdata.py\", line 313, in pdb_to_cg\n",
            "    return self.cg_model(\n",
            "           ^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libcg.py\", line 248, in __init__\n",
            "    super().__init__(pdb_fn, dcd_fn, **kwarg)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libcg.py\", line 44, in __init__\n",
            "    super().__init__(pdb_fn, dcd_fn, is_all=is_all, **kwarg)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libpdb.py\", line 20, in __init__\n",
            "    pdb = mdtraj.load(pdb_fn, standard_names=False)\n",
            "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 396, in load\n",
            "    kwargs[\"top\"] = _parse_topology(\n",
            "                    ^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 170, in _parse_topology\n",
            "    _traj = load_frame(top, 0, **kwargs)\n",
            "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 309, in load_frame\n",
            "    _assert_files_exist(filename)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 108, in _assert_files_exist\n",
            "    raise OSError(\"No such file: %s\" % fn)\n",
            "OSError: No such file: PED00082_C14_S00_GT.pdb\n",
            "\n",
            "\n",
            "STDOUT: \n",
            "Processing: PED00082_C21_S00_GT.pdb -> /content/drive/MyDrive/clustered_ensemble_outputs/PED00082_C21_S00_GT.all.pdb\n",
            "处理 PED00082_C21_S00_GT.pdb 时出错:\n",
            "返回码: 1\n",
            "STDERR: Traceback (most recent call last):\n",
            "  File \"/usr/local/bin/convert_cg2all\", line 8, in <module>\n",
            "    sys.exit(main())\n",
            "             ^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/script/convert_cg2all.py\", line 190, in main\n",
            "    batch = next(iter(input_s)).to(device)\n",
            "            ^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py\", line 630, in __next__\n",
            "    data = self._next_data()\n",
            "           ^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py\", line 1344, in _next_data\n",
            "    return self._process_data(data)\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py\", line 1370, in _process_data\n",
            "    data.reraise()\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/_utils.py\", line 706, in reraise\n",
            "    raise exception\n",
            "OSError: Caught OSError in DataLoader worker process 0.\n",
            "Original Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/_utils/worker.py\", line 309, in _worker_loop\n",
            "    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]\n",
            "           ^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/_utils/fetch.py\", line 52, in fetch\n",
            "    data = [self.dataset[idx] for idx in possibly_batched_index]\n",
            "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/utils/data/_utils/fetch.py\", line 52, in <listcomp>\n",
            "    data = [self.dataset[idx] for idx in possibly_batched_index]\n",
            "            ~~~~~~~~~~~~^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libdata.py\", line 333, in __getitem__\n",
            "    cg = self.pdb_to_cg(self.pdb_fn)\n",
            "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libdata.py\", line 313, in pdb_to_cg\n",
            "    return self.cg_model(\n",
            "           ^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libcg.py\", line 248, in __init__\n",
            "    super().__init__(pdb_fn, dcd_fn, **kwarg)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libcg.py\", line 44, in __init__\n",
            "    super().__init__(pdb_fn, dcd_fn, is_all=is_all, **kwarg)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/cg2all/lib/libpdb.py\", line 20, in __init__\n",
            "    pdb = mdtraj.load(pdb_fn, standard_names=False)\n",
            "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 396, in load\n",
            "    kwargs[\"top\"] = _parse_topology(\n",
            "                    ^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 170, in _parse_topology\n",
            "    _traj = load_frame(top, 0, **kwargs)\n",
            "            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 309, in load_frame\n",
            "    _assert_files_exist(filename)\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/mdtraj/core/trajectory.py\", line 108, in _assert_files_exist\n",
            "    raise OSError(\"No such file: %s\" % fn)\n",
            "OSError: No such file: PED00082_C21_S00_GT.pdb\n",
            "\n",
            "\n",
            "STDOUT: \n"
          ]
        },
        {
          "output_type": "error",
          "ename": "NameError",
          "evalue": "name 'input_pdb' is not defined",
          "traceback": [
            "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
            "\u001b[0;31mNameError\u001b[0m                                 Traceback (most recent call last)",
            "\u001b[0;32m<ipython-input-14-20f13bc59ced>\u001b[0m in \u001b[0;36m<cell line: 0>\u001b[0;34m()\u001b[0m\n\u001b[1;32m     90\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     91\u001b[0m \u001b[0;31m# 合并结果\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 92\u001b[0;31m \u001b[0mfinal_output\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mpathlib\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mPath\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0minput_pdb\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mstem\u001b[0m \u001b[0;34m+\u001b[0m \u001b[0;34m\"_multi.all.pdb\"\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     93\u001b[0m \u001b[0;32mwith\u001b[0m \u001b[0mopen\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mfinal_output\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m'w'\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0moutfile\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     94\u001b[0m     \u001b[0;32mfor\u001b[0m \u001b[0mi\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mpdb\u001b[0m \u001b[0;32min\u001b[0m \u001b[0menumerate\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0moutput_files\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
            "\u001b[0;31mNameError\u001b[0m: name 'input_pdb' is not defined"
          ]
        }
      ],
      "source": [
        "#@title Task 2: Conversion of a CG model to an all-atom structure using __convert_cg2all__\n",
        "\n",
        "!pip install biopython\n",
        "# upload a PDB file\n",
        "import os\n",
        "import requests\n",
        "from google.colab import files, drive\n",
        "from pathlib import Path\n",
        "import subprocess\n",
        "import tempfile\n",
        "from Bio.PDB import PDBParser, PDBIO\n",
        "\n",
        "coarse_grained_model_type = \"CalphaBasedModel\" #@param [\"CalphaBasedModel\", \"ResidueBasedModel\", \"SidechainModel\", \"CalphaCMModel\", \"CalphaSCModel\", \"BackboneModel\", \"MainchainModel\", \"Martini\", \"Martini3\", \"PRIMO\"]\n",
        "\n",
        "use_example = False #@param {type:\"boolean\"}\n",
        "#@markdown - An example input PDB file will be downloaded from [our repository](https://github.com/huhlim/cg2all/tree/main/tests).\n",
        "\n",
        "def split_models(pdb_file):\n",
        "    parser = PDBParser(QUIET=True)\n",
        "    structure = parser.get_structure('input', pdb_file)\n",
        "    temp_files = []\n",
        "\n",
        "    for model in structure:\n",
        "        temp_pdb = tempfile.NamedTemporaryFile(delete=False, suffix=\".pdb\")\n",
        "        temp_io = PDBIO()\n",
        "        temp_io.set_structure(model)\n",
        "        temp_io.save(temp_pdb.name)\n",
        "        temp_files.append(temp_pdb.name)\n",
        "\n",
        "    return temp_files\n",
        "\n",
        "if use_example:\n",
        "    url = {\"CalphaBasedModel\": \"https://raw.githubusercontent.com/huhlim/cg2all/main/tests/1ab1_A.calpha.pdb\", \\\n",
        "           \"ResidueBasedModel\": \"https://raw.githubusercontent.com/huhlim/cg2all/main/tests/1ab1_A.residue.pdb\", \\\n",
        "           \"SidechainModel\": \"https://raw.githubusercontent.com/huhlim/cg2all/main/tests/1ab1_A.sc.pdb\", \\\n",
        "           \"CalphaCMModel\": \"https://raw.githubusercontent.com/huhlim/cg2all/main/tests/1ab1_A.cacm.pdb\", \\\n",
        "           \"CalphaSCModel\": \"https://raw.githubusercontent.com/huhlim/cg2all/main/tests/1ab1_A.casc.pdb\", \\\n",
        "           \"BackboneModel\": \"https://raw.githubusercontent.com/huhlim/cg2all/main/tests/1ab1_A.bb.pdb\", \\\n",
        "           \"MainchainModel\": \"https://raw.githubusercontent.com/huhlim/cg2all/main/tests/1ab1_A.mc.pdb\", \\\n",
        "           \"Martini\": \"https://raw.githubusercontent.com/huhlim/cg2all/main/tests/1ab1_A.martini.pdb\", \\\n",
        "           \"Martini3\": \"https://raw.githubusercontent.com/huhlim/cg2all/main/tests/1ab1_A.martini3.pdb\", \\\n",
        "           \"PRIMO\": \"https://raw.githubusercontent.com/huhlim/cg2all/main/tests/1ab1_A.primo.pdb\"}\n",
        "    url = url[coarse_grained_model_type]\n",
        "    input_pdb = url.split(\"/\")[-1]\n",
        "    with open(input_pdb, \"wt\") as fout:\n",
        "        fout.write(requests.get(url).text)\n",
        "else:\n",
        "    drive.mount('/content/drive')\n",
        "    input_folder = \"/content/drive/MyDrive/clustered_ensemble_inputs\"\n",
        "    output_folder = \"/content/drive/MyDrive/clustered_ensemble_outputs\"\n",
        "    # 确保输出目录存在\n",
        "    os.makedirs(output_folder, exist_ok=True)\n",
        "\n",
        "    # 验证输入目录是否存在\n",
        "    if not os.path.exists(input_folder):\n",
        "        raise FileNotFoundError(f\"输入目录不存在: {input_folder}\")\n",
        "\n",
        "# 获取输入文件列表（带完整路径）\n",
        "model_pdbs = [os.path.join(input_folder, f) for f in os.listdir(input_folder) if f.endswith(\".pdb\")]\n",
        "\n",
        "output_files = []\n",
        "coarse_grained_model_type = \"CalphaBasedModel\"  # 确保此变量已定义\n",
        "\n",
        "# 处理每个输入文件\n",
        "for model_pdb in model_pdbs:\n",
        "    # 构造输出文件路径\n",
        "    output_stem = Path(model_pdb).stem + \".all.pdb\"\n",
        "    output_pdb = os.path.join(output_folder, output_stem)\n",
        "\n",
        "    try:\n",
        "        # 检查文件是否存在\n",
        "        if not os.path.exists(model_pdb):\n",
        "            raise FileNotFoundError(f\"输入文件不存在: {model_pdb}\")\n",
        "\n",
        "        # 调用外部命令（显式指定工作目录）\n",
        "        subprocess.run(\n",
        "            [\n",
        "                \"convert_cg2all\",\n",
        "                \"-p\", os.path.basename(model_pdb),  # 传递文件名（假设工具在输入目录中工作）\n",
        "                \"-o\", os.path.basename(output_pdb),  # 同样传递文件名\n",
        "                \"--cg\", coarse_grained_model_type\n",
        "            ],\n",
        "            cwd=input_folder,  # 在输入目录中执行命令\n",
        "            check=True\n",
        "        )\n",
        "        output_files.append(output_pdb)\n",
        "\n",
        "    except subprocess.CalledProcessError as e:\n",
        "        print(f\"处理 {model_pdb} 时出错:\")\n",
        "        print(\"STDERR:\", e.stderr)\n",
        "        continue\n",
        "\n",
        "# 合并结果（修复变量名）\n",
        "if output_files:\n",
        "    # 使用第一个输出文件的主干名生成最终输出名\n",
        "    first_output = output_files[0]\n",
        "    final_output = os.path.join(\n",
        "        output_folder,\n",
        "        Path(first_output).stem + \"_multi.all.pdb\"\n",
        "    )\n",
        "\n",
        "    # 合并多个 .all.pdb 文件（示例代码）\n",
        "    with open(final_output, 'w') as outfile:\n",
        "        for fname in output_files:\n",
        "            with open(fname, 'r') as infile:\n",
        "                outfile.write(infile.read())\n",
        "else:\n",
        "    print(\"没有生成任何输出文件，无法合并。\")\n",
        "\n",
        "print(f\"Converted {input_pdb} in {coarse_grained_model_type} to {final_output}\")\n",
        "\n",
        "display(output_pdb, representation=\"cartoon\").show()\n",
        "\n",
        "# 清理临时文件\n",
        "# for f in model_pdbs + output_files:\n",
        "#    pathlib.Path(f).unlink()"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "qKtrbblH-29X"
      },
      "outputs": [],
      "source": [
        "#@title Download the converted file\n",
        "files.download(output_pdb)"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "G0m80ahGdAev"
      },
      "source": [
        "---"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "cellView": "form",
        "id": "u4e5NhxndAQ8"
      },
      "outputs": [],
      "source": [
        "#@title Task 3: Conversion of a CG simulation trajectory to an atomistic simulation trajectory using __convert_cg2all__\n",
        "#@markdown Input trajectory file should be in the DCD format.\n",
        "\n",
        "# upload a PDB file\n",
        "import requests\n",
        "from google.colab import files\n",
        "\n",
        "coarse_grained_model_type = \"CalphaBasedModel\" #@param [\"CalphaBasedModel\", \"ResidueBasedModel\", \"SidechainModel\", \"CalphaCMModel\", \"CalphaSCModel\", \"BackboneModel\", \"MainchainModel\", \"Martini\", \"Martini3\", \"PRIMO\"]\n",
        "\n",
        "use_example = True #@param {type:\"boolean\"}\n",
        "#@markdown - An example input PDB and DCD files will be downloaded from [our repository](https://github.com/huhlim/cg2all/tree/main/tests).\n",
        "\n",
        "if use_example:\n",
        "    if coarse_grained_model_type != \"CalphaBasedModel\":\n",
        "        print(\"The example is based on CalphaBasedModel.\")\n",
        "        coarse_grained_model_type = \"CalphaBasedModel\"\n",
        "    #\n",
        "    url = \"https://raw.githubusercontent.com/huhlim/cg2all/main/tests/1jni.calpha.pdb\"\n",
        "    input_pdb = url.split(\"/\")[-1]\n",
        "    with open(input_pdb, \"wt\") as fout:\n",
        "        fout.write(requests.get(url).text)\n",
        "    #\n",
        "    url = \"https://raw.githubusercontent.com/huhlim/cg2all/main/tests/1jni.calpha.dcd\"\n",
        "    input_dcd = url.split(\"/\")[-1]\n",
        "    with open(input_dcd, \"wb\") as fout:\n",
        "        fout.write(requests.get(url).content)\n",
        "\n",
        "else:\n",
        "    input_pdb = files.upload()\n",
        "    input_pdb = list(input_pdb)[0]\n",
        "    input_dcd = files.upload()\n",
        "    input_dcd = list(input_dcd)[0]\n",
        "\n",
        "batch_size = 1 #@param {type: \"number\"}\n",
        "#@markdown - Batch size should be a divisor of the total number of frames. The example trajectory file has five frames.\n",
        "\n",
        "# convert\n",
        "import pathlib\n",
        "output_dcd = pathlib.Path(input_dcd).stem + \".all.dcd\"\n",
        "output_pdb = pathlib.Path(input_pdb).stem + \".all.pdb\"\n",
        "\n",
        "!convert_cg2all -p $input_pdb --dcd $input_dcd -o $output_dcd -opdb $output_pdb --cg $coarse_grained_model_type --batch $batch_size\n",
        "print(f\"Converted {input_dcd} in {coarse_grained_model_type} to {output_dcd}\")\n",
        "\n",
        "import mdtraj\n",
        "pdb = mdtraj.load(input_pdb)\n",
        "traj = mdtraj.load(output_dcd, top=output_pdb)\n",
        "if len(traj) > 20:\n",
        "    print(\"Displaying first 20 frames\")\n",
        "    traj = traj[:20]\n",
        "traj = traj.superpose(traj)\n",
        "traj.save(\"display.pdb\")\n",
        "#\n",
        "display(\"display.pdb\", representation=\"cartoon\", is_traj=True).show()\n",
        "#print(\"Displaying the last frame\")\n",
        "#display(output_pdb, representation=\"cartoon\").show()"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "cellView": "form",
        "id": "Fc3MtzNU5kCa"
      },
      "outputs": [],
      "source": [
        "#@title Download the converted file\n",
        "files.download(output_pdb)\n",
        "files.download(output_dcd)"
      ]
    }
  ],
  "metadata": {
    "colab": {
      "provenance": [],
      "gpuType": "T4",
      "include_colab_link": true
    },
    "kernelspec": {
      "display_name": "Python 3",
      "name": "python3"
    },
    "language_info": {
      "name": "python"
    },
    "accelerator": "GPU"
  },
  "nbformat": 4,
  "nbformat_minor": 0
}